sonar.projectKey=sard_cases
sonar.projectName=sard_cases
sonar.sources=./test_cases
sonar.host.url=http://localhost:9000
sonar.token=sqp_7ae3173620220e6647f389d112e5ebd5888cc77a
sonar.java.binaries=test_cases/
