sonar.projectKey=sard_cases
sonar.projectName=sard_cases
sonar.host.url=http://localhost:9000
sonar.sources=test_cases
sonar.java.binaries=test_cases/**/classes
sonar.java.libraries=./lib/*.jar,../test_cases/bin/support_classes
sonar.java.source=11
sonar.sourceEncoding=UTF-8
